### ISSUE TITLE
Help button

### ISSUE THREAD

**Issue by joshwahwalters** [pmeas/pmeas-frontend#33] opened 2017-03-03 04:31 UTC
To ensure users understand how the GUI functions there should be a 'help' icon that pops up a window with detailed instructions on how to connect ports, set effects and submit to the back end.

**Comment by mattfg** [comment] 2017-03-10 22:57
Duplicate of #49 closing this and keeping that open because it encompasses this

**Closed as completed by mattfg** 2017-03-10 22:57 UTC
Labels: Type: Feature, Priority: Medium, Difficulty: Medium
